In [1]:
#importing libraries
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.datasets import load_wine

In [4]:
#loading the dataset
wine=load_wine()

In [5]:
wine.data.shape

(178, 13)

In [6]:
wine.target.shape

(178,)

In [7]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [8]:
df=pd.DataFrame(wine.data)

In [9]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [10]:
df=df.iloc[:,1:]

In [11]:
df

1     2     3      4     5     6     7     8      9     10    11  \
0    1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29   5.64  1.04  3.92   
1    1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28   4.38  1.05  3.40   
2    2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81   5.68  1.03  3.17   
3    1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18   7.80  0.86  3.45   
4    2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82   4.32  1.04  2.93   
..    ...   ...   ...    ...   ...   ...   ...   ...    ...   ...   ...   
173  5.65  2.45  20.5   95.0  1.68  0.61  0.52  1.06   7.70  0.64  1.74   
174  3.91  2.48  23.0  102.0  1.80  0.75  0.43  1.41   7.30  0.70  1.56   
175  4.28  2.26  20.0  120.0  1.59  0.69  0.43  1.35  10.20  0.59  1.56   
176  2.59  2.37  20.0  120.0  1.65  0.68  0.53  1.46   9.30  0.60  1.62   
177  4.10  2.74  24.5   96.0  2.05  0.76  0.56  1.35   9.20  0.61  1.60   

         12  
0    1065.0  
1    1050.0  
2    1185.0  
3    1480.0  
4     735.0  
..      ...  
173   740.0  
174   750.0  
175   835.0  
176   840.0  
177   560.0  

[178 rows x 12 columns]

In [12]:
target_df=pd.DataFrame(wine.target)

In [13]:
target_df

0
0    0
1    0
2    0
3    0
4    0
..  ..
173  2
174  2
175  2
176  2
177  2

[178 rows x 1 columns]

In [14]:
X_train,X_test,y_train,y_test=train_test_split(df,target_df,random_state=24,test_size=0.3)

In [15]:
X_test.shape

(54, 12)

In [16]:
LR = LogisticRegression()

In [17]:
LR.fit(X_train,y_train)

LogisticRegression()

In [18]:
y_pred = LR.predict(X_test)

In [19]:
#determining score of training and test dataset
print("Training score",LR.score(X_train,y_train))
print("Test set score",LR.score(X_test,y_test))

Training score 0.9758064516129032
Test set score 0.9629629629629629


In [20]:
conf_mat = confusion_matrix(y_test,y_pred)
print("Confusion Matrix is: \n",conf_mat)

Confusion Matrix is: 
 [[20  1  0]
 [ 0 19  1]
 [ 0  0 13]]
